### ISSUE TITLE
[feature request] add isonline(provider)

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGeo/TileProviders.jl#1]
or `ishealthy(provider)`, `healthcheck(provider)`, that makes sure the connection is stable, so we can check before downloading lots of tiles and then getting long wait times and lots of retries/connection errors at once.

**Comment by rafaqz** [comment]
Maybe in MapTiles.jl? It has HTTP deps

**Comment by SimonDanisch** [comment]
Ah ok, that makes sense ;)
