### ISSUE TITLE
Link to documents broken

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaGeo/TileProviders.jl#18]
Link from ReadMe to documents broken for both stable and dev

**Comment by felixcremer** [comment]
Apparently there are no docs apartfrom the readme. The docs folder is from the initial commit and there is no GH action.

**Comment by rafaqz** [comment]
Theres an action on CI.yml

We need to set the branch in Documentation workflow to `main` as its trying to use `master`

**Comment by rafaqz** [comment]
Fixed, stable will link when registration goes through
