### ISSUE TITLE
Stamen Maps has Moved

### ISSUE THREAD

**Issue by nateybear** [JuliaGeo/TileProviders.jl#22]
As of October 31, 2023, Stamen Maps are no longer available at the Fastly URL that they currently point to. The tile server is now hosted by Stadia Maps:

`https://tiles.stadiamaps.com/tiles/{variant}/{z}/{x}/{y}{r}.{ext}`

Where `variant` is now `stamen_toner`, `stamen_toner_background`, etc.

Since there is already a Stadia TileProvider, I imagine the path forward will be removing Stamen as a tile provider and adding the stamen variants to `TileProviders.Stadia`.

[Reference](https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/)

**Comment by asinghvi17** [comment]
Aha, this should probably have been a breaking release...this is causing Leaflet tests to fail :D

**Comment by rafaqz** [comment]
Sorry thats on me

**Comment by asinghvi17** [comment]
Looks like this has been fixed, thanks folks!
